# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# Settings
envs:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://signoz-otel-collector.signoz.svc.cluster.local:4318"

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-nginx-production
  hosts:
    - host: pydemoapp.k8s.rtcalc.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: pydemoapp-tls
      hosts:
        - pydemoapp.k8s.rtcalc.com
